# Generated by Django 4.0 on 2021-12-27 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hash', models.BinaryField(max_length=64)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.domain')),
            ],
        ),
    ]
