# Generated by Django 4.0 on 2021-12-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64)),
                ('zone', models.CharField(max_length=12)),
                ('real_domain', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
