# Generated by Django 4.0 on 2021-12-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="signing",
            field=models.BinaryField(max_length=64, null=True),
        ),
    ]
