# Generated by Django 4.0 on 2021-12-28 12:54

from django.db import migrations, models
import index.models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=index.models.gen_id,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exception", models.TextField()),
                ("timestamp", models.IntegerField(default=time.time)),
            ],
        ),
    ]
